spring.application.name=Spring Boot Demo
spring.profiles.active=dev
server.port=8080
# Configurazione MySQL (esempio)
spring.datasource.url=jdbc:mysql://localhost:3306/MyCourseBoot
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.username=root
spring.datasource.password=KHJuial0a100?
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
#IMPLEMENTAZIONE GOOGLE RECAPTCHA V2
google.recaptcha.key.site=6LecltQqAAAAAN95Fpd0tNPaP3btuQYcbZezbq4W
google.recaptcha.key.secret=6LecltQqAAAAACbndR7013fLeTyAaNu2Lf3y3qE5
#STRIPE O PAYPAL
payment.config.key.type=paypal
#PAYPAL
paypal.client.id=AU79gkDiXlpiTSgpybwY5Wut4sxe6DG2ihsaVvIPCV7egBjTRJUYcSSc5_nv27fRCRsVUA-TbCIO4ypC
paypal.client.secret=EMXfEAjxhYPGYBRdQ6UQApTI-tvDKbAB6_fKikJ2e83eHauMZRtLLrzdF0HyfL9AuZZuml4b-Qklbe2z
paypal.mode=sandbox
#STRIPE
stripe.secret.key=sk_test_51QpNkvIX50JfMIoYVkJTzSvG9D5A7UjAqNkvAJ4teqNjBdvT4AkfzosuTAGyl3oP0MGHTRb1puok6wTBIbnn7Af000XyMmsrlE
#MAIL TRAP
mail.trap.key.user=d8fa39dfb8c174
mail.trap.key.password=4825d478f84b82